name: isolate_functions
description: A Flutter plugin to run functions in a separate isolate. this plugin simplifies the process of running functions in a separate isolate and getting the result back.
version: 1.0.4
repository: https://github.com/nikaeene/isolate_functions

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.foroodja.isolate_functions
        pluginClass: IsolateFunctionsPlugin
      ios:
        pluginClass: IsolateFunctionsPlugin
      linux:
        pluginClass: IsolateFunctionsPlugin
      macos:
        pluginClass: IsolateFunctionsPlugin
      windows:
        pluginClass: IsolateFunctionsPluginCApi

